# Generated by Django 4.0.3 on 2022-03-10 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10, verbose_name='brand_name')),
                ('link', models.URLField(blank=True, max_length=20, null=True, verbose_name='website')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('link', models.URLField(max_length=30, verbose_name='source')),
                ('processor', models.TextField(max_length=50)),
                ('memory', models.TextField(max_length=50)),
                ('graphics', models.TextField(max_length=50)),
                ('storage', models.TextField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('category', models.TextField(choices=[('CPU', 'Processor'), ('GPU', 'Graphics Card'), ('RAM', 'Memory'), ('DISK', 'Storage')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('link', models.URLField(max_length=30)),
                ('update_time', models.DateTimeField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.brand')),
            ],
        ),
    ]
