# Generated by Django 4.0.3 on 2022-04-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0005_laptop_qnty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, verbose_name='brand_name'),
        ),
        migrations.AlterField(
            model_name='component',
            name='link',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='link',
            field=models.URLField(max_length=255, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
