# Generated by Django 4.0.3 on 2022-04-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0007_laptop_slug_alter_component_name_alter_laptop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='slug',
            field=models.SlugField(default='SLUG', max_length=255),
        ),
    ]
