# Generated by Django 4.0.3 on 2022-05-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0009_alter_laptop_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('CPU', 'Processor'), ('GPU', 'Graphics Card'), ('RAM', 'Memory'), ('DISK', 'Storage')], max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='graphics',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='storage',
        ),
        migrations.AddField(
            model_name='laptop',
            name='graphics',
            field=models.ManyToManyField(related_name='meGPU', to='laptop.memo'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='memory',
            field=models.ManyToManyField(related_name='meRAM', to='laptop.memo'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor',
            field=models.ManyToManyField(related_name='meCPU', to='laptop.memo'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage',
            field=models.ManyToManyField(related_name='meDISK', to='laptop.memo'),
        ),
    ]
