# Generated by Django 4.0.3 on 2022-05-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0010_memo_remove_laptop_graphics_remove_laptop_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
