# Generated by Django 4.0.3 on 2022-05-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0011_alter_memo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnty', models.IntegerField(default=1, help_text='Distinct Component Quantity')),
            ],
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='graphics',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='storage',
        ),
        migrations.AddField(
            model_name='laptop',
            name='specs',
            field=models.ManyToManyField(related_name='specs', through='laptop.LaptopNote', to='laptop.memo'),
        ),
        migrations.AddField(
            model_name='laptopnote',
            name='laptop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.laptop'),
        ),
        migrations.AddField(
            model_name='laptopnote',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.memo'),
        ),
    ]
