# Generated by Django 4.0.3 on 2022-05-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0012_laptopnote_remove_laptop_graphics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='qnty',
        ),
    ]
