# Generated by Django 4.0.3 on 2022-06-02 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0013_remove_laptop_qnty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopnote',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_detail', to='laptop.memo'),
        ),
    ]
