# Generated by Django 4.0.3 on 2022-12-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0014_alter_laptopnote_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='specs_price_difference',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
