# Generated by Django 4.0.3 on 2023-02-10 20:31

from django.db import migrations, models
import laptop.models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0015_laptop_specs_price_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=laptop.models.brand_directory_path),
        ),
        migrations.AddField(
            model_name='laptop',
            name='image_display',
            field=models.ImageField(blank=True, null=True, upload_to=laptop.models.laptop_directory_path),
        ),
    ]
