# Generated by Django 4.0.3 on 2022-03-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='update_time',
        ),
        migrations.AddField(
            model_name='component',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
