# Generated by Django 4.0.3 on 2022-03-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_remove_component_update_time_component_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='link',
            field=models.URLField(blank=True, max_length=50, null=True, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=125, verbose_name='brand_name'),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('CPU', 'Processor'), ('GPU', 'Graphics Card'), ('RAM', 'Memory'), ('DISK', 'Storage')], max_length=5),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='graphics',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='memory',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.TextField(max_length=125),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.CharField(max_length=125),
        ),
    ]
