# Generated by Django 4.0.3 on 2022-03-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0003_alter_brand_link_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(max_length=125),
        ),
    ]
