# Generated by Django 4.0.3 on 2022-04-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0004_alter_laptop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='qnty',
            field=models.CharField(default='1,1,1,1', max_length=20),
        ),
    ]
