# Generated by Django 4.0.3 on 2022-04-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0008_alter_laptop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
