# Generated by Django 4.0.3 on 2022-10-27 19:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laptop', '0014_alter_laptopnote_memo'),
        ('user', '0002_userimpression_remove_profile_id_profile_imp_laptop_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
