# Generated by Django 4.0.3 on 2022-10-27 19:34

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_profile_userprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
