# Generated by Django 4.0.3 on 2022-10-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
