# Generated by Django 4.0.3 on 2022-12-01 01:02

from django.db import migrations, models
import oauth2_provider.generators
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='oauth2_client_secret',
            field=models.CharField(blank=True, default=oauth2_provider.generators.generate_client_secret, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path),
        ),
    ]
