# Generated by Django 4.0.3 on 2022-12-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userprofile_oauth2_client_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='oauth2_client_secret',
        ),
    ]
