name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    environment: Django
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL}}
    runs-on: ubuntu-latest

    steps:
    - name: Set GitHub Action Env
      run: |
        echo "python_version=3.10" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.python_version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: laptopspecs
      run: |
        python manage.py test
